version: '3.8'

services: 
    web:
        build: .
        command: python /projects/manage.py runserver 0.0.0.0:8000

        volumes: 
            - .:/projects
        ports: 
            - 8000:8000