# Generated by Django 3.1 on 2021-11-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
