# Generated by Django 3.1 on 2021-11-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customer_braintree_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Order',
        ),
    ]
